# Generated by Django 4.1.5 on 2023-01-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.ForeignKey(default='General', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main.topic'),
        ),
    ]
