# Generated by Django 4.1.5 on 2023-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topic_alter_thread_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.CharField(max_length=20),
        ),
    ]
